### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Exey** [mnemocron/TelegramChatStats#4]
```bash
python3 telegram-statistics.py -i result.json
importing raw data...
input data is a single chat export
calculating metrics...
Traceback (most recent call last):
  File "/Users/exey/Desktop/TelegramChatStats/telegram-statistics.py", line 196, in <module>
    main()
  File "/Users/exey/Desktop/TelegramChatStats/telegram-statistics.py", line 175, in main
    calculate_metrics(chat_data, date_filter)
  File "/Users/exey/Desktop/TelegramChatStats/telegram-statistics.py", line 107, in calculate_metrics
    metrics = _message_numerics(chat_data, date_filter)
  File "/Users/exey/Desktop/TelegramChatStats/_message_numerics.py", line 29, in _message_numerics
    if metrics['A']['name'] in message['from']:
TypeError: argument of type 'NoneType' is not iterable```

**Comment by mnemocron** [comment]
Hi Exey, I just exported a single chat and generated the graphs with the same command as yours.
I cannot reproduce the issue.

I suspect, that the very first message in the chat is not human generated, but rather an auto generated message.
Is your result.json a Whatsapp or Telegram export?
