### ISSUE TITLE
KeyError: 'from'

### ISSUE THREAD

**Issue by danzerzine** [mnemocron/TelegramChatStats#8]
Hi, I've followed the instruction, but get the following error message, could you please point to possible solution? 

```python
importing raw data...
input data is a single chat export
calculating metrics...
Traceback (most recent call last):
  File "telegram-statistics.py", line 267, in <module>
    main()
  File "telegram-statistics.py", line 209, in main
    calculate_metrics(chat_data, date_filter)
  File "telegram-statistics.py", line 137, in calculate_metrics
    metrics = _message_numerics(chat_data, date_filter)
  File "/work/_message_numerics.py", line 24, in _message_numerics
    metrics["A"]["name"] = chat["messages"][1]["from"]
KeyError: 'from'

```

**Comment by aleks648** [comment]
I'm having the identical issue.

**Comment by mnemocron** [comment]
What type of chat are you exporting @aleks648 and @danzerzine ?
Is it from a group, or a bot?
I just tested it with two different single chat exports and I cannot reproduce the problem.

**Comment by celgus** [comment]
> What type of chat are you exporting @aleks648 and @danzerzine ? Is it from a group, or a bot? I just tested it with two different single chat exports and I cannot reproduce the problem.

"type": "public_supergroup",
